"""Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms."""


def fibonacci(bound):
    fibonacci_list = [0, 1]
    while fibonacci_list[-1] + fibonacci_list[-2] < bound:
        fibonacci_list.append(fibonacci_list[-1] + fibonacci_list[-2])
    return fibonacci_list


print(sum(fibonacci(4_000_000)))
