"""
Consider all integer combinations of a**b for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5
If they are then placed in numerical order, with any repeats removed,
we get the following sequence of 15 distinct terms:
4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125
How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
"""


def main():
    """returns the number of unique terms in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100"""
    term_set = set()
    for integer in range(2, 101):
        for power in range(2, 101):
            term_set.add(integer ** power)
    return len(term_set)


print(main())
